src/Entity/Autor.php
<?php

namespace App\Entity;

use App\Repository\AutorRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AutorRepository::class)]
class Autor
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nombre = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $nacionalidad = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_nacimiento = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_fallecimiento = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getNacionalidad(): ?string
    {
        return $this->nacionalidad;
    }

    public function setNacionalidad(?string $nacionalidad): static
    {
        $this->nacionalidad = $nacionalidad;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fecha_nacimiento;
    }

    public function setFechaNacimiento(?\DateTimeInterface $fecha_nacimiento): static
    {
        $this->fecha_nacimiento = $fecha_nacimiento;

        return $this;
    }

    public function getFechaFallecimiento(): ?\DateTimeInterface
    {
        return $this->fecha_fallecimiento;
    }

    public function setFechaFallecimiento(?\DateTimeInterface $fecha_fallecimiento): static
    {
        $this->fecha_fallecimiento = $fecha_fallecimiento;

        return $this;
    }
}

src/Form/AutorType.php
<?php

namespace App\Form;

use App\Entity\Autor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AutorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
            ->add('nacionalidad')
            ->add('fecha_nacimiento', null, [
                'widget' => 'single_text',
            ])
            ->add('fecha_fallecimiento', null, [
                'widget' => 'single_text',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Autor::class,
        ]);
    }
}

src/Controller/AutorController.php
<?php

namespace App\Controller;

use App\Entity\Autor;
use App\Form\AutorType;
use App\Repository\AutorRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/autor')]
final class AutorController extends AbstractController
{
    #[Route(name: 'app_autor_index', methods: ['GET'])]
    public function index(AutorRepository $autorRepository): Response
    {
        return $this->render('autor/index.html.twig', [
            'autors' => $autorRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_autor_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $autor = new Autor();
        $form = $this->createForm(AutorType::class, $autor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($autor);
            $entityManager->flush();

            return $this->redirectToRoute('app_autor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('autor/new.html.twig', [
            'autor' => $autor,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_autor_show', methods: ['GET'])]
    public function show(Autor $autor): Response
    {
        return $this->render('autor/show.html.twig', [
            'autor' => $autor,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_autor_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Autor $autor, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AutorType::class, $autor);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_autor_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('autor/edit.html.twig', [
            'autor' => $autor,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_autor_delete', methods: ['POST'])]
    public function delete(Request $request, Autor $autor, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$autor->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($autor);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_autor_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/autor/_delete_form.html.twig
<form method="post" action="{{ path('app_autor_delete', {'id': autor.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ autor.id) }}">
    <button class="btn">Delete</button>
</form>

templates/autor/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Autor{% endblock %}

{% block body %}
    <h1>Edit Autor</h1>

    {{ include('autor/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_autor_index') }}">back to list</a>

    {{ include('autor/_delete_form.html.twig') }}
{% endblock %}

templates/autor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Autor index{% endblock %}

{% block body %}
    <h1>Autor index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Nacionalidad</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for autor in autors %}
            <tr>
                <td>{{ autor.nombre }}</td>
                <td>{{ autor.nacionalidad }}</td>
{#                <td>{{ autor.fechaNacimiento ? autor.fechaNacimiento|date('Y-m-d') : '' }}</td>#}
{#                <td>{{ autor.fechaFallecimiento ? autor.fechaFallecimiento|date('Y-m-d') : '' }}</td>#}
                <td>
                    <a href="{{ path('app_autor_show', {'id': autor.id}) }}">show</a>
                    <a href="{{ path('app_autor_edit', {'id': autor.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_autor_new') }}">Create new</a>
{% endblock %}

templates/autor/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Autor{% endblock %}

{% block body %}
    <h1>Create new Autor</h1>

    {{ include('autor/_form.html.twig') }}

    <a href="{{ path('app_autor_index') }}">back to list</a>
{% endblock %}

templates/autor/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Autor{% endblock %}

{% block body %}
    <h1>Autor</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nombre</th>
                <td>{{ autor.nombre }}</td>
            </tr>
            <tr>
                <th>Nacionalidad</th>
                <td>{{ autor.nacionalidad }}</td>
            </tr>
            <tr>
                <th>Fecha de nacimiento</th>
                <td>{{ autor.fechaNacimiento ? autor.fechaNacimiento|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Fecha de fallecimiento</th>
                <td>{{ autor.fechaFallecimiento ? autor.fechaFallecimiento|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_autor_index') }}">back to list</a>

    <a href="{{ path('app_autor_edit', {'id': autor.id}) }}">edit</a>

    {{ include('autor/_delete_form.html.twig') }}
{% endblock %}