src/Entity/Prestamo.php
<?php

namespace App\Entity;

use App\Repository\PrestamoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PrestamoRepository::class)]
class Prestamo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ejemplar $ejemplar = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Usuario $usuario = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fecha_prestamo = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fecha_devolucion_prevista = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_devolucion_real = null;

    #[ORM\Column(length: 10)]
    private ?string $estado = null;

    public function __construct()
    {
        $this->fecha_prestamo = new \DateTime();
        $this->fecha_devolucion_prevista = (new \DateTime())->modify('+7 days');
    }

    public function __toString(): string
    {
        return $this->usuario->getNombre() . ' - ' . $this->ejemplar->getLibro()->getTitulo();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEjemplar(): ?Ejemplar
    {
        return $this->ejemplar;
    }

    public function setEjemplar(?Ejemplar $ejemplar): static
    {
        $this->ejemplar = $ejemplar;

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): static
    {
        $this->usuario = $usuario;

        return $this;
    }

    public function getFechaPrestamo(): ?\DateTimeInterface
    {
        return $this->fecha_prestamo;
    }

    public function setFechaPrestamo(\DateTimeInterface $fecha_prestamo): static
    {
        $this->fecha_prestamo = $fecha_prestamo;

        return $this;
    }

    public function getFechaDevolucionPrevista(): ?\DateTimeInterface
    {
        return $this->fecha_devolucion_prevista;
    }

    public function setFechaDevolucionPrevista(\DateTimeInterface $fecha_devolucion_prevista): static
    {
        $this->fecha_devolucion_prevista = $fecha_devolucion_prevista;

        return $this;
    }

    public function getFechaDevolucionReal(): ?\DateTimeInterface
    {
        return $this->fecha_devolucion_real;
    }

    public function setFechaDevolucionReal(?\DateTimeInterface $fecha_devolucion_real): static
    {
        $this->fecha_devolucion_real = $fecha_devolucion_real;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): static
    {
        $this->estado = $estado;

        return $this;
    }
}

src/Form/PrestamoType.php
<?php

namespace App\Form;

use App\Entity\Ejemplar;
use App\Entity\Libro;
use App\Entity\Prestamo;
use App\Entity\Usuario;
use App\Repository\LibroRepository;
use App\Repository\PrestamoRepository;
use App\Repository\UsuarioRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PrestamoType extends AbstractType
{
    public function __construct(
        private readonly UsuarioRepository $usuarioRepository,
        private readonly PrestamoRepository $prestamoRepository,
    )
    {
    }
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $roles = ['ROLE_ALUMNO', 'ROLE_PROFESOR', 'ROLE_INVITADO'];
        $prestamoId = $builder->getData()->getId();
        $ejemplarId = $this->obtenerEjemplarSeleccionado($prestamoId);
        $usuarioId = $this->obtenerUsuarioSeleccionado($prestamoId);

        $builder
            ->add('libro', EntityType::class, [
                'class' => Libro::class,
                'choice_label' => 'titulo',
//                'choices' => $this->libroRepository->librosConEjemplaresDisponibles(),
                'query_builder' => function (LibroRepository $repository) use ($ejemplarId) {
                    return $repository->librosConEjemplaresDisponibles($ejemplarId);
                },
                'mapped' => false
            ])
            ->add('usuario', EntityType::class, [
                'class' => Usuario::class,
                'choice_label' => 'nombre',
                'query_builder' => function (UsuarioRepository $repository) use ($roles, $usuarioId) {
                    return $repository->usuariosPorRoles($roles, $usuarioId);
                }
//                'choices' => $this->usuarioRepository->usuariosPorRoles($roles),
            ])
            ->add('fecha_prestamo', null, [
                'widget' => 'single_text',
            ])
            ->add('fecha_devolucion_prevista', null, [
                'widget' => 'single_text',
            ])
            ->add('fecha_devolucion_real', null, [
                'widget' => 'single_text'
            ])
            ->add('estado', HiddenType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Prestamo::class,
        ]);
    }

    private function obtenerEjemplarSeleccionado(?int $prestamoId): array
    {
        return $this->prestamoRepository->idEjemplar($prestamoId);
    }

    private function obtenerUsuarioSeleccionado(?int $prestamoId): array
    {
        return $this->prestamoRepository->idUsuario($prestamoId);
    }
}

src/Controller/PrestamoController.php
<?php

namespace App\Controller;

use App\Entity\Ejemplar;
use App\Entity\Prestamo;
use App\Form\PrestamoType;
use App\Repository\EjemplarRepository;
use App\Repository\PrestamoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/prestamo')]
final class PrestamoController extends AbstractController
{
    #[Route(name: 'app_prestamo_index', methods: ['GET'])]
    public function index(PrestamoRepository $prestamoRepository, EntityManagerInterface $entityManager): Response
    {
        // Obtener todos los préstamos no devueltos
        $prestamos = $entityManager->getRepository(Prestamo::class)->findBy(['estado' => 'activo']);

        // Obtener la fecha actual
        $hoy = new \DateTime();
        $update = false;

        // Verificar y actualizar estado de retraso
        foreach ($prestamos as $prestamo) {
            $fechaDevolucionPrevista = $prestamo->getFechaDevolucionPrevista();

            if ($hoy > $fechaDevolucionPrevista) {
                $prestamo->setEstado('retrasado');
                $prestamo->getUsuario()->setEstado('suspendido');
                $entityManager->persist($prestamo);
                $update = true;
            }
        }

        if ($update) $entityManager->flush();

        // Obtener todos los préstamos actualizados
//        $prestamos = $entityManager->getRepository(Prestamo::class)->findAll();
        return $this->render('prestamo/index.html.twig', [
            'prestamos' => $prestamoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_prestamo_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, EjemplarRepository $ejemplarRepository): Response
    {
        $prestamo = new Prestamo();
        $form = $this->createForm(PrestamoType::class, $prestamo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $libro = $form->get('libro')->getData();
            $ejemplar = $ejemplarRepository->findOneBy([
                'libro' => $libro,
                'estado' => 'disponible',
            ]);

            if ($ejemplar) {
                $prestamo->setEjemplar($ejemplar);
                $ejemplar->setEstado('prestado');
                $prestamo->setEstado('activo');
//                $prestamo->setFechaDevolucionReal(new \DateTime('0000-00-00'));
                $entityManager->persist($prestamo);
                $entityManager->flush();

                return $this->redirectToRoute('app_prestamo_index', [], Response::HTTP_SEE_OTHER);
            } else {
                $this->addFlash('error', 'No hay ejemplares disponibles para este libro.');
            }
        }

        return $this->render('prestamo/new.html.twig', [
            'prestamo' => $prestamo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_prestamo_show', methods: ['GET'])]
    public function show(Prestamo $prestamo): Response
    {
        return $this->render('prestamo/show.html.twig', [
            'prestamo' => $prestamo,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_prestamo_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Prestamo $prestamo, EntityManagerInterface $entityManager): Response
    {
        $ejemplar = new Ejemplar();
        $form = $this->createForm(PrestamoType::class, $prestamo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($prestamo->getFechaDevolucionReal() !== null) {
                $prestamo->setEstado('devuelto');
                $ejemplar = $prestamo->getEjemplar();
                $ejemplar?->setEstado('disponible');

//                $usuario = $prestamo->getUsuario();
//                $usuario?->setEstado('activo');
            }
            $entityManager->flush();

            return $this->redirectToRoute('app_prestamo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('prestamo/edit.html.twig', [
            'prestamo' => $prestamo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_prestamo_delete', methods: ['POST'])]
    public function delete(Request $request, Prestamo $prestamo, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$prestamo->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($prestamo);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_prestamo_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/prestamo/_delete_form.html.twig
<form style="display: inline-block" method="post" action="{{ path('app_prestamo_delete', {'id': prestamo.id}) }}">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ prestamo.id) }}">
    <button type="button" class="btn btn-sm btn-outline-danger rounded-3" data-coreui-toggle="modal" data-coreui-target="#deleteEditorial">
        <i class="fa fa-trash"></i>
    </button>
</form>

templates/prestamo/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Prestamo{% endblock %}

{% block body %}
    <h1>Edit Prestamo</h1>

    {{ include('prestamo/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_prestamo_index') }}">back to list</a>

    {{ include('prestamo/_delete_form.html.twig') }}
{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function() {
            $('#prestamo_fecha_prestamo').on('change', function() {
                let fechaPrestamo = new Date($(this).val());

                if (!isNaN(fechaPrestamo)) {
                    fechaPrestamo.setDate(fechaPrestamo.getDate() + 7);

                    // Formatear la fecha a YYYY-MM-DD para que sea compatible con el input date
                    let fechaFormateada = fechaPrestamo.toISOString().split('T')[0];

                    $('#prestamo_fecha_devolucion_prevista').val(fechaFormateada);
                }
            });
        });
    </script>
{% endblock %}

templates/prestamo/index.html.twig
{% import 'macro/actions.html.twig' as actions %}
{% extends 'base.html.twig' %}

{% block title %}Prestamos{% endblock %}

{% block body %}
    <div class="d-flex justify-content-between align-items-center">
        <h1 class="mb-4 d-flex align-items-center gap-3">
            <svg class="nav-icon" style="height: 40px; width: 40px">
                <use xlink:href="{{ asset('vendors/@coreui/icons/svg/free.svg#cil-transfer') }}"></use>
            </svg> Prestamos
        </h1>
        <a class="btn btn-success rounded-3" href="{{ path('app_prestamo_new') }}">
            <i class="fa-solid fa-circle-plus"></i> Agregar
        </a>
    </div>

    <table class="table table-hover">
        <thead class="table-dark">
            <tr>
                <th>Usuario</th>
                <th>Libro</th>
                <th>Fecha_prestamo</th>
                <th>Fecha_devolucion_prevista</th>
{#                <th>Fecha_devolucion_real</th>#}
                <th>Estado</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for prestamo in prestamos %}
            <tr>
                <td>{{ prestamo.usuario.nombre }}</td>
                <td>{{ prestamo.ejemplar.libro.titulo }}</td>
                <td>{{ prestamo.fechaPrestamo ? prestamo.fechaPrestamo|date('d-m-Y') : '' }}</td>
                <td>{{ prestamo.fechaDevolucionPrevista ? prestamo.fechaDevolucionPrevista|date('d-m-Y') : '' }}</td>
{#                <td>{{ prestamo.fechaDevolucionReal ? prestamo.fechaDevolucionReal|date('Y-m-d') : '' }}</td>#}
                <td>
                    {% if prestamo.estado == 'activo' %}
                        <span class="badge bg-success">Activo</span>
                    {% elseif prestamo.estado == 'devuelto' %}
                        <span class="badge" style="background-color: darkorange">Devuelto</span>
                    {% else %}
                        <span class="badge bg-danger">Retrasado</span>
                    {% endif %}
                </td>
                <td>
{#                    <a href="{{ path('app_prestamo_show', {'id': prestamo.id}) }}">show</a>#}
{#                    <a href="{{ path('app_prestamo_edit', {'id': prestamo.id}) }}">edit</a>#}
                    {{ actions.btn_show(path('app_prestamo_show', {'id': prestamo.id})) }}
                    {{ actions.btn_edit(path('app_prestamo_edit', {'id': prestamo.id})) }}
                    <button type="button" class="btn btn-sm btn-outline-danger rounded-3" data-coreui-toggle="modal" data-coreui-target="#deleteModal"
                            data-id="{{ prestamo.id }}"
                            data-token="{{ csrf_token('delete' ~ prestamo.id) }}"
                            data-action="{{ path('app_prestamo_delete', {'id': '__ID__'}) }}"
                            onclick="setDeleteFormAction(this)">
                        <i class="fa fa-trash"></i>
                    </button>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">No se encontraron registros</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% include 'components/delete_modal.html.twig' %}
{% endblock %}

templates/prestamo/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Prestamo{% endblock %}

{% block body %}
    <h1>Create new Prestamo</h1>

    {{ include('prestamo/_form.html.twig') }}

    <a href="{{ path('app_prestamo_index') }}">back to list</a>
{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function(){
            $('#prestamo_fecha_prestamo').on('change', function(){
                let fechaPrestamo = $(this).val();

                if (fechaPrestamo) {
                    let dateObj = new Date(fechaPrestamo);
                    dateObj.setDate(dateObj.getDate() + 8);

                    let anio = dateObj.getFullYear();
                    let mes = (dateObj.getMonth() + 1).toString().padStart(2, '0');
                    let dia = dateObj.getDate().toString().padStart(2, '0');
                    let nuevaFecha = anio + '-' + mes + '-' + dia;

                    $('#prestamo_fecha_devolucion_prevista').val(nuevaFecha);
                }
            });
        });
    </script>
{% endblock %}

templates/prestamo/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prestamo{% endblock %}

{% block body %}
    <h1>Prestamo</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Libro</th>
                <td>{{ prestamo.ejemplar.libro.titulo }}</td>
            </tr>
            <tr>
                <th>Ejemplar</th>
                <td>{{ prestamo.ejemplar.codigo }}</td>
            </tr>
            <tr>
                <th>Usuario</th>
                <td>{{ prestamo.usuario.nombre }}</td>
            </tr>
            <tr>
                <th>Fecha de prestamo</th>
                <td>{{ prestamo.fechaPrestamo ? prestamo.fechaPrestamo|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Fecha de devolucion prevista</th>
                <td>{{ prestamo.fechaDevolucionPrevista ? prestamo.fechaDevolucionPrevista|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Fecha de devolucion real</th>
                <td>{{ prestamo.fechaDevolucionReal ? prestamo.fechaDevolucionReal|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ prestamo.estado }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_prestamo_index') }}">back to list</a>

    <a href="{{ path('app_prestamo_edit', {'id': prestamo.id}) }}">edit</a>

    {{ include('prestamo/_delete_form.html.twig') }}
{% endblock %}