src/Entity/Ejemplar.php
<?php

namespace App\Entity;

use App\Repository\EjemplarRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EjemplarRepository::class)]
class Ejemplar
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'ejemplares')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Libro $libro = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $codigo = null;

    #[ORM\Column(length: 13, nullable: true)]
    private ?string $estado = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_adquisicion = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibro(): ?Libro
    {
        return $this->libro;
    }

    public function setLibro(?Libro $libro): static
    {
        $this->libro = $libro;

        return $this;
    }

    public function getCodigo(): ?string
    {
        return $this->codigo;
    }

    public function setCodigo(string $codigo): static
    {
        $this->codigo = $codigo;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): static
    {
        $this->estado = $estado;

        return $this;
    }

    public function getFechaAdquisicion(): ?\DateTimeInterface
    {
        return $this->fecha_adquisicion;
    }

    public function setFechaAdquisicion(?\DateTimeInterface $fecha_adquisicion): static
    {
        $this->fecha_adquisicion = $fecha_adquisicion;

        return $this;
    }
}

src/Entity/Libro.php
<?php

namespace App\Entity;

use App\Repository\LibroRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LibroRepository::class)]
class Libro
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $titulo = null;

    #[ORM\Column(length: 14)]
    private ?string $isbn = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $anio_publicacion = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Editorial $editorial = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categoria $categoria = null;

    /**
     * @var Collection<int, Autor>
     */
    #[ORM\ManyToMany(targetEntity: Autor::class)]
    private Collection $autor;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $idioma = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $descripcion = null;

    /**
     * @var Collection<int, Ejemplar>
     */
    #[ORM\OneToMany(targetEntity: Ejemplar::class, mappedBy: 'libro', cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $ejemplares;

    public function __construct()
    {
        $this->autor = new ArrayCollection();
        $this->ejemplares = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): static
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): static
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getAnioPublicacion(): ?int
    {
        return $this->anio_publicacion;
    }

    public function setAnioPublicacion(?int $anio_publicacion): static
    {
        $this->anio_publicacion = $anio_publicacion;

        return $this;
    }

    public function getEditorial(): ?Editorial
    {
        return $this->editorial;
    }

    public function setEditorial(?Editorial $editorial): static
    {
        $this->editorial = $editorial;

        return $this;
    }

    public function getCategoria(): ?Categoria
    {
        return $this->categoria;
    }

    public function setCategoria(?Categoria $categoria): static
    {
        $this->categoria = $categoria;

        return $this;
    }

    /**
     * @return Collection<int, Autor>
     */
    public function getAutor(): Collection
    {
        return $this->autor;
    }

    public function addAutor(Autor $autor): static
    {
        if (!$this->autor->contains($autor)) {
            $this->autor->add($autor);
        }

        return $this;
    }

    public function removeAutor(Autor $autor): static
    {
        $this->autor->removeElement($autor);

        return $this;
    }

    public function getIdioma(): ?string
    {
        return $this->idioma;
    }

    public function setIdioma(?string $idioma): static
    {
        $this->idioma = $idioma;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(?string $descripcion): static
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * @return Collection<int, Ejemplar>
     */
    public function getEjemplares(): Collection
    {
        return $this->ejemplares;
    }

    public function addEjemplare(Ejemplar $ejemplar): static
    {
        if (!$this->ejemplares->contains($ejemplar)) {
            $this->ejemplares->add($ejemplar);
            $ejemplar->setLibro($this);
        }

        return $this;
    }

    public function removeEjemplare(Ejemplar $ejemplar): static
    {
        if ($this->ejemplares->removeElement($ejemplar)) {
            // set the owning side to null (unless already changed)
            if ($ejemplar->getLibro() === $this) {
                $ejemplar->setLibro(null);
            }
        }

        return $this;
    }

//    public function getEstado(): string
//    {
//        foreach ($this->ejemplares as $ejemplar) {
//            return $ejemplar->getEstado() !== null ? 'disponible': 'pendiente';
//        }
//        return 'prestado';
//    }
}

src/Form/LibroType.php
<?php

namespace App\Form;

use App\Entity\Autor;
use App\Entity\Categoria;
use App\Entity\Editorial;
use App\Entity\Libro;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LibroType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titulo')
            ->add('isbn')
            ->add('anio_publicacion')
            ->add('idioma')
            ->add('descripcion')
            ->add('editorial', EntityType::class, [
                'class' => Editorial::class,
                'choice_label' => 'nombre',
            ])
            ->add('categoria', EntityType::class, [
                'class' => Categoria::class,
                'choice_label' => 'nombre',
            ])
            ->add('autor', EntityType::class, [
                'class' => Autor::class,
                'choice_label' => 'nombre',
                'multiple' => true,
            ])
            ->add('ejemplares', CollectionType::class, [
                'entry_type' => EjemplarType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Libro::class,
        ]);
    }
}

src/Controller/LibroController.php
<?php

namespace App\Controller;

use App\Entity\Libro;
use App\Form\LibroType;
use App\Repository\EjemplarRepository;
use App\Repository\LibroRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/libro')]
final class LibroController extends AbstractController
{
    #[Route(name: 'app_libro_index', methods: ['GET'])]
    public function index(LibroRepository $libroRepository): Response
    {
        return $this->render('libro/index.html.twig', [
//            'libros' => $libroRepository->findAll(),
            'libros' => $libroRepository->estadosLibro(),
        ]);
    }

    #[Route('/new', name: 'app_libro_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $libro = new Libro();
        $form = $this->createForm(LibroType::class, $libro);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($libro);
            $entityManager->flush();

            foreach ($libro->getEjemplares() as $ejemplar) {
                $numEjemplar = $ejemplar->getCodigo();
                $codigo = sprintf('LIB-%d-%03d', $libro->getId(), $numEjemplar);
                $ejemplar->setCodigo($codigo);

                $ejemplar->setEstado('disponible');

                $ejemplar->setLibro($libro);

                $entityManager->persist($ejemplar);
            }
            $entityManager->flush();

            return $this->redirectToRoute('app_libro_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('libro/new.html.twig', [
            'libro' => $libro,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_libro_show', methods: ['GET'])]
    public function show(Libro $libro): Response
    {
        return $this->render('libro/show.html.twig', [
            'libro' => $libro,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_libro_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Libro $libro, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LibroType::class, $libro);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($libro->getEjemplares() as $ejemplar) {
                if ($ejemplar->getId() === null) {
                    $numEjemplar = $ejemplar->getCodigo();
                    $codigo = sprintf('LIB-%d-%03d', $libro->getId(), $numEjemplar);
                    $ejemplar->setCodigo($codigo);

                    $ejemplar->setEstado('disponible');

                    $ejemplar->setLibro($libro);

                    $entityManager->persist($ejemplar);
                }
            }
            $entityManager->flush();
            return $this->redirectToRoute('app_libro_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('libro/edit.html.twig', [
            'libro' => $libro,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_libro_delete', methods: ['POST'])]
    public function delete(Request $request, Libro $libro, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$libro->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($libro);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_libro_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/libro/_delete_form.html.twig
<form method="post" action="{{ path('app_libro_delete', {'id': libro.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ libro.id) }}">
    <button class="btn">Delete</button>
</form>

templates/libro/_form.html.twig
{% import 'macro/actions.html.twig' as actions %}

{{ form_start(form) }}
{#    {{ form_widget(form) }}#}
    {{ form_row(form.titulo) }}
    {{ form_row(form.isbn) }}
    {{ form_row(form.anio_publicacion) }}
    {{ form_row(form.idioma) }}
    {{ form_row(form.descripcion) }}
    {{ form_row(form.editorial) }}
    {{ form_row(form.categoria) }}
    {{ form_row(form.autor) }}
    {{ actions.collection(form.ejemplares) }}

    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/libro/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Libro{% endblock %}

{% block body %}
    <h1>Edit Libro</h1>

    {{ include('libro/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_libro_index') }}">back to list</a>

    {{ include('libro/_delete_form.html.twig') }}
{% endblock %}

{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#libro_autor').select2();
        });
    </script>

    <script src="{{ asset('js/collection.js') }}"></script>
{% endblock %}

templates/libro/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Libro index{% endblock %}

{% block body %}
    <h1>Libro index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Titulo</th>
                <th>Isbn</th>
                <th>Año de publicacion</th>
                <th>Idioma</th>
                <th>Estado</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for libro in libros %}
            <tr>
                <td>{{ libro.titulo }}</td>
                <td>{{ libro.isbn }}</td>
                <td>{{ libro.anio_publicacion }}</td>
                <td>{{ libro.idioma }}</td>
                <td>
                    {% if libro.estado == 'Disponible' %}
                        <span style="color: green; font-weight: bold;">Disponible</span>
                        <span>({{ libro.disponibles }})</span>
                    {% elseif libro.estado == 'Prestado' %}
                        <span style="color: red; font-weight: bold;">Prestado</span>
                    {% else %}
                        <span style="color: darkorange; font-weight: bold;">Pendiente</span>
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('app_libro_show', {'id': libro.id}) }}">show</a>
                    <a href="{{ path('app_libro_edit', {'id': libro.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_libro_new') }}">Create new</a>
{% endblock %}

templates/libro/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Libro{% endblock %}

{% block body %}
    <h1>Create new Libro</h1>

    {{ include('libro/_form.html.twig') }}

    <a href="{{ path('app_libro_index') }}">back to list</a>
{% endblock %}

{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#libro_autor').select2();
        });
    </script>

    <script src="{{ asset('js/collection.js') }}"></script>
{% endblock %}

templates/libro/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Libro{% endblock %}

{% block body %}
    <h1>Libro</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Titulo</th>
                <td>{{ libro.titulo }}</td>
            </tr>
            <tr>
                <th>Isbn</th>
                <td>{{ libro.isbn }}</td>
            </tr>
            <tr>
                <th>Año de publicacion</th>
                <td>{{ libro.anioPublicacion }}</td>
            </tr>
            <tr>
                <th>Editorial</th>
                <td>{{ libro.editorial.nombre }}</td>
            </tr>
            <tr>
                <th>Categoria</th>
                <td>{{ libro.categoria.nombre }}</td>
            </tr>
            <tr>
                <th>Autor(es)</th>
                <td>
                    <ul>
                        {% for autor in libro.autor %}
                            <li>{{ autor.nombre }}</li>
                        {% else %}
                            <li>No hay autores asociados a este libro.</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            <tr>
                <th>Idioma</th>
                <td>{{ libro.idioma }}</td>
            </tr>
            <tr>
                <th>Descripcion</th>
                <td>{{ libro.descripcion }}</td>
            </tr>
            <tr>
                <th>Ejemplares</th>
                <td>
                    <ul>
                        {% for ejemplar in libro.ejemplares %}
                            <li>
                                <strong>Código:</strong> {{ ejemplar.codigo }}<br>
                                <strong>Estado:</strong> {{ ejemplar.estado }}<br>
                                <strong>Fecha de Adquisición:</strong> {{ ejemplar.fechaAdquisicion|date('d/m/Y') }}
                            </li>
                        {% else %}
                            <li>No hay ejemplares asociados a este libro.</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_libro_index') }}">back to list</a>

    <a href="{{ path('app_libro_edit', {'id': libro.id}) }}">edit</a>

    {{ include('libro/_delete_form.html.twig') }}
{% endblock %}